// ============================================
// LUXUDIES - Sample Product Data
// ============================================

import type { Product, Collection, Review, ComboOffer } from '@/types';

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    name: 'Enchanted Bow Pendant Necklace',
    slug: 'enchanted-bow-pendant-necklace',
    description: 'A delicate bow pendant adorned with sparkling zirconia stones, suspended on a beaded satellite chain. This piece embodies feminine grace with its intricate ribbon design, making it the perfect statement of everyday elegance.',
    short_description: 'Delicate bow pendant with sparkling zirconia on a beaded chain.',
    category: 'necklaces',
    price: 149,
    compare_at_price: 299,
    sku: 'LXD-NK-001',
    stock: 50,
    is_active: true,
    is_featured: true,
    is_bestseller: true,
    is_new: false,
    benefits: ['anti-tarnish', 'lightweight', 'water-resistant', 'hypoallergenic', '18k-gold'],
    care_instructions: 'Store in the provided pouch. Avoid contact with perfumes and chemicals. Wipe gently with a soft cloth after wear.',
    styling_tips: 'Layer with a simple chain for a chic stacked look, or wear alone for understated elegance. Perfect for both casual outings and evening events.',
    images: [
      { id: 'img_1', product_id: 'prod_1', url: '/images/products/bow-necklace.jpg', alt_text: 'Enchanted Bow Pendant Necklace on satin', position: 0, is_primary: true },
    ],
    variants: [],
    collections: ['everyday-elegance', 'bestsellers'],
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'prod_2',
    name: 'Celestial Pearl Drop Earrings',
    slug: 'celestial-pearl-drop-earrings',
    description: 'Ethereal pearl drops cradled in a crescent of gold — these earrings capture the beauty of moonlit evenings. The freshwater pearls are hand-selected for their lustrous sheen, set in 18K gold-plated brass.',
    short_description: 'Freshwater pearl drops in gold crescent setting.',
    category: 'earrings',
    price: 129,
    compare_at_price: 249,
    sku: 'LXD-ER-001',
    stock: 35,
    is_active: true,
    is_featured: true,
    is_bestseller: false,
    is_new: true,
    benefits: ['anti-tarnish', 'lightweight', 'hypoallergenic', '18k-gold'],
    care_instructions: 'Store separately to prevent scratching. Remove before swimming or bathing.',
    styling_tips: 'A timeless addition to any outfit — from boardroom meetings to evening celebrations.',
    images: [
      { id: 'img_2', product_id: 'prod_2', url: '/images/products/product-3.jpg', alt_text: 'Celestial Pearl Drop Earrings', position: 0, is_primary: true },
    ],
    variants: [],
    collections: ['pearl-collection', 'new-arrivals'],
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-02-01T10:00:00Z',
  },
  {
    id: 'prod_3',
    name: 'Golden Radiance Hoop Earrings',
    slug: 'golden-radiance-hoop-earrings',
    description: 'Bold yet refined, these sunburst-textured hoops catch light from every angle. The fan-shaped design adds a touch of modern artistry to the classic hoop silhouette.',
    short_description: 'Sunburst-textured statement hoops in 18K gold.',
    category: 'earrings',
    price: 99,
    compare_at_price: 199,
    sku: 'LXD-ER-002',
    stock: 60,
    is_active: true,
    is_featured: true,
    is_bestseller: true,
    is_new: false,
    benefits: ['anti-tarnish', 'lightweight', 'water-resistant', '18k-gold'],
    care_instructions: 'Wipe clean after each wear. Store in anti-tarnish pouch.',
    styling_tips: 'Pair with a sleek updo to let these hoops take center stage.',
    images: [
      { id: 'img_3', product_id: 'prod_3', url: '/images/products/product-4.jpg', alt_text: 'Golden Radiance Hoop Earrings', position: 0, is_primary: true },
    ],
    variants: [],
    collections: ['everyday-elegance', 'bestsellers'],
    created_at: '2026-01-20T10:00:00Z',
    updated_at: '2026-01-20T10:00:00Z',
  },
  {
    id: 'prod_4',
    name: 'Infinity Love Pendant Chain',
    slug: 'infinity-love-pendant-chain',
    description: 'An eternal symbol of connection and devotion, this infinity pendant features pavé-set zirconia stones on a delicate cable chain. Gift-ready and meaningful.',
    short_description: 'Pavé infinity pendant on a delicate cable chain.',
    category: 'necklaces',
    price: 179,
    compare_at_price: 349,
    sku: 'LXD-NK-002',
    stock: 40,
    is_active: true,
    is_featured: false,
    is_bestseller: true,
    is_new: false,
    benefits: ['anti-tarnish', 'lightweight', 'gift-ready', 'hypoallergenic', '18k-gold'],
    care_instructions: 'Store flat to prevent chain tangling. Avoid water exposure.',
    styling_tips: 'The perfect gift for anniversaries, birthdays, or just because. Layers beautifully with chokers.',
    images: [
      { id: 'img_4', product_id: 'prod_4', url: '/images/products/product-5.jpg', alt_text: 'Infinity Love Pendant Chain', position: 0, is_primary: true },
    ],
    variants: [],
    collections: ['gift-sets', 'bestsellers'],
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'prod_5',
    name: 'Regal Chain Bracelet',
    slug: 'regal-chain-bracelet',
    description: 'A finely crafted chain bracelet that transitions effortlessly from day to night. The interlocking links create a fluid, luxurious movement on the wrist.',
    short_description: 'Interlocking gold chain bracelet with adjustable clasp.',
    category: 'bracelets',
    price: 119,
    compare_at_price: 229,
    sku: 'LXD-BR-001',
    stock: 45,
    is_active: true,
    is_featured: true,
    is_bestseller: false,
    is_new: true,
    benefits: ['anti-tarnish', 'lightweight', 'water-resistant', '18k-gold'],
    care_instructions: 'Remove before exercise. Clean with jewelry polishing cloth.',
    styling_tips: 'Stack with other bracelets or wear alone for minimal elegance.',
    images: [
      { id: 'img_5', product_id: 'prod_5', url: '/images/products/product-6.jpg', alt_text: 'Regal Chain Bracelet', position: 0, is_primary: true },
    ],
    variants: [],
    collections: ['everyday-elegance', 'new-arrivals'],
    created_at: '2026-02-15T10:00:00Z',
    updated_at: '2026-02-15T10:00:00Z',
  },
  {
    id: 'prod_6',
    name: 'Timeless Solitaire Ring',
    slug: 'timeless-solitaire-ring',
    description: 'A single brilliant zirconia stone set in a slim gold band — pure, elegant, and unforgettable. This ring celebrates the beauty of simplicity.',
    short_description: 'Single zirconia stone on a slim 18K gold band.',
    category: 'rings',
    price: 89,
    compare_at_price: 179,
    sku: 'LXD-RG-001',
    stock: 55,
    is_active: true,
    is_featured: false,
    is_bestseller: false,
    is_new: true,
    benefits: ['anti-tarnish', 'lightweight', 'hypoallergenic', '18k-gold'],
    care_instructions: 'Remove before hand washing. Store in ring slot of jewelry box.',
    styling_tips: 'Stack with thin gold bands or wear solo for a whisper of sparkle.',
    images: [
      { id: 'img_6', product_id: 'prod_6', url: '/images/products/product-7.jpg', alt_text: 'Timeless Solitaire Ring', position: 0, is_primary: true },
    ],
    variants: [],
    collections: ['everyday-elegance', 'new-arrivals'],
    created_at: '2026-02-20T10:00:00Z',
    updated_at: '2026-02-20T10:00:00Z',
  },
  {
    id: 'prod_7',
    name: '3 Iconic Earrings Set',
    slug: '3-iconic-earrings-set',
    description: 'Three styles, endless charm. This curated set includes our fan-textured studs, crescent hoops, and heart huggie earrings — all in 18K gold plating. Perfect for those who love variety.',
    short_description: 'Curated set of 3 iconic earring styles in 18K gold.',
    category: 'earrings',
    price: 249,
    compare_at_price: 397,
    sku: 'LXD-ER-SET-001',
    stock: 30,
    is_active: true,
    is_featured: true,
    is_bestseller: true,
    is_new: false,
    benefits: ['anti-tarnish', 'lightweight', 'water-resistant', 'gift-ready', 'hypoallergenic', '18k-gold'],
    care_instructions: 'Store each pair separately. Clean with soft cloth. Avoid chemicals.',
    styling_tips: 'Mix and match for different moods. Fan studs for work, hearts for dates, crescents for weekends.',
    images: [
      { id: 'img_7', product_id: 'prod_7', url: '/images/products/iconic-earrings-combo.jpg', alt_text: '3 Iconic Earrings Set', position: 0, is_primary: true },
    ],
    variants: [],
    collections: ['combo-offers', 'gift-sets', 'bestsellers'],
    created_at: '2026-01-05T10:00:00Z',
    updated_at: '2026-01-05T10:00:00Z',
  },
  {
    id: 'prod_8',
    name: 'Whisper Thin Layering Necklace',
    slug: 'whisper-thin-layering-necklace',
    description: 'An ultra-fine gold chain designed to be layered or worn alone for whisper-light elegance. Adjustable length with a delicate extension chain.',
    short_description: 'Ultra-fine gold layering chain, adjustable length.',
    category: 'necklaces',
    price: 79,
    compare_at_price: 149,
    sku: 'LXD-NK-003',
    stock: 70,
    is_active: true,
    is_featured: false,
    is_bestseller: false,
    is_new: true,
    benefits: ['anti-tarnish', 'lightweight', 'water-resistant', '18k-gold'],
    care_instructions: 'Store flat, avoid tangling with other chains.',
    styling_tips: 'Layer with 2-3 chains of varying length for the perfect stacked look.',
    images: [
      { id: 'img_8', product_id: 'prod_8', url: '/images/products/product-3.jpg', alt_text: 'Whisper Thin Layering Necklace', position: 0, is_primary: true },
    ],
    variants: [],
    collections: ['everyday-elegance', 'new-arrivals'],
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-03-01T10:00:00Z',
  },
];

export const SAMPLE_COLLECTIONS: Collection[] = [
  {
    id: 'col_1',
    name: 'Everyday Elegance',
    slug: 'everyday-elegance',
    description: 'Minimal yet beautiful. Pieces designed for your everyday moments.',
    image_url: '/images/products/bow-necklace.jpg',
    position: 0,
  },
  {
    id: 'col_2',
    name: 'Festive Collection',
    slug: 'festive-collection',
    description: 'Shine for every celebration. Bold, beautiful, and festive.',
    image_url: '/images/products/product-4.jpg',
    position: 1,
  },
  {
    id: 'col_3',
    name: 'Pearl Collection',
    slug: 'pearl-collection',
    description: 'Classic pearls, timeless charm. Elegance that never fades.',
    image_url: '/images/products/product-3.jpg',
    position: 2,
  },
  {
    id: 'col_4',
    name: 'Gift Sets',
    slug: 'gift-sets',
    description: 'Perfect for your special ones. Curated with love.',
    image_url: '/images/products/iconic-earrings-combo.jpg',
    position: 3,
  },
];

export const SAMPLE_REVIEWS: Review[] = [
  {
    id: 'rev_1',
    user_id: 'user_1',
    product_id: 'prod_1',
    rating: 5,
    title: 'Absolutely stunning!',
    body: 'The quality is amazing for the price. I bought this for my sister\'s birthday and she was in tears. The packaging was beautiful too. Will definitely order again!',
    images: [],
    is_verified: true,
    is_approved: true,
    user_name: 'Priya M.',
    user_avatar: null,
    created_at: '2026-02-10T10:00:00Z',
  },
  {
    id: 'rev_2',
    user_id: 'user_2',
    product_id: 'prod_7',
    rating: 5,
    title: 'Best combo ever!',
    body: 'All three earrings are gorgeous. The fan ones are my daily go-to now. Gold color is exactly like real gold. Zero irritation on my sensitive ears.',
    images: [],
    is_verified: true,
    is_approved: true,
    user_name: 'Sneha R.',
    user_avatar: null,
    created_at: '2026-02-15T10:00:00Z',
  },
  {
    id: 'rev_3',
    user_id: 'user_3',
    product_id: 'prod_3',
    rating: 4,
    title: 'Love the design',
    body: 'Very lightweight and comfortable. I wear them all day at work. The anti-tarnish coating really works — still shiny after 3 months!',
    images: [],
    is_verified: true,
    is_approved: true,
    user_name: 'Deepa K.',
    user_avatar: null,
    created_at: '2026-03-01T10:00:00Z',
  },
  {
    id: 'rev_4',
    user_id: 'user_4',
    product_id: 'prod_4',
    rating: 5,
    title: 'Perfect gift for my wife',
    body: 'Ordered this for our anniversary. The infinity symbol is so meaningful. She loves it and wears it every day. Packaging was gift-ready.',
    images: [],
    is_verified: true,
    is_approved: true,
    user_name: 'Arjun S.',
    user_avatar: null,
    created_at: '2026-03-10T10:00:00Z',
  },
  {
    id: 'rev_5',
    user_id: 'user_5',
    product_id: 'prod_1',
    rating: 5,
    title: 'Exceeded expectations',
    body: 'I was skeptical ordering jewelry online, but this necklace changed my mind. The bow pendant is delicate and beautiful. Fast shipping too!',
    images: [],
    is_verified: true,
    is_approved: true,
    user_name: 'Kavitha L.',
    user_avatar: null,
    created_at: '2026-03-15T10:00:00Z',
  },
];

export const SAMPLE_COMBOS: ComboOffer[] = [
  {
    id: 'combo_1',
    name: 'The Complete Elegance Set',
    slug: 'complete-elegance-set',
    description: 'Our bestselling necklace paired with matching earrings — a complete look for any occasion.',
    image_url: '/images/products/iconic-earrings-combo.jpg',
    product_ids: ['prod_1', 'prod_3'],
    products: [],
    combo_price: 199,
    original_price: 348,
    savings: 149,
    is_active: true,
  },
  {
    id: 'combo_2',
    name: 'The Gift Box Collection',
    slug: 'gift-box-collection',
    description: 'Three stunning pieces in premium gift packaging. Perfect for birthdays, anniversaries, or treating yourself.',
    image_url: '/images/products/bow-necklace.jpg',
    product_ids: ['prod_1', 'prod_2', 'prod_6'],
    products: [],
    combo_price: 299,
    original_price: 527,
    savings: 228,
    is_active: true,
  },
  {
    id: 'combo_3',
    name: 'Everyday Essentials Bundle',
    slug: 'everyday-essentials-bundle',
    description: 'Your daily jewelry essentials — a layering chain, classic hoops, and a slim ring.',
    image_url: '/images/products/product-6.jpg',
    product_ids: ['prod_8', 'prod_3', 'prod_6'],
    products: [],
    combo_price: 219,
    original_price: 427,
    savings: 208,
    is_active: true,
  },
];

export const FAQ_DATA = [
  {
    id: 'faq_1',
    question: 'Is LUXUDIES jewelry real gold?',
    answer: 'Our jewelry is 18K gold-plated over high-quality brass, offering the luxurious look and feel of real gold at an accessible price. Each piece is coated with anti-tarnish protection for long-lasting shine.',
  },
  {
    id: 'faq_2',
    question: 'Is it safe for sensitive skin?',
    answer: 'Absolutely. All LUXUDIES pieces are hypoallergenic, nickel-free, and lead-free. They are designed to be gentle on even the most sensitive skin.',
  },
  {
    id: 'faq_3',
    question: 'Can I wear it in water?',
    answer: 'Our jewelry is water and sweat resistant, perfect for everyday wear. However, we recommend removing your pieces before swimming in chlorinated pools or applying chemicals.',
  },
  {
    id: 'faq_4',
    question: 'How long will the gold color last?',
    answer: 'With our anti-tarnish coating, your jewelry will maintain its golden shine for a long time. Following our care instructions will help preserve its beauty even longer.',
  },
  {
    id: 'faq_5',
    question: 'What is your shipping policy?',
    answer: 'We offer FREE shipping across Tamil Nadu on all orders. Orders are typically delivered within 3-7 business days. You\'ll receive tracking details once your order is shipped.',
  },
  {
    id: 'faq_6',
    question: 'What is your return policy?',
    answer: 'We offer a 7-day return policy. If you\'re not satisfied with your purchase, contact us within 7 days of delivery for a hassle-free return or exchange.',
  },
  {
    id: 'faq_7',
    question: 'Do you offer gift packaging?',
    answer: 'Yes! Every LUXUDIES piece comes in premium gift-ready packaging with a velvet pouch and branded box. Perfect for gifting without any extra effort.',
  },
  {
    id: 'faq_8',
    question: 'How can I track my order?',
    answer: 'Once your order is shipped, you\'ll receive an SMS and email with your tracking link. You can also track your order anytime on our Track Order page.',
  },
];
